(function() {var implementors = {};
implementors["wasmtime"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.i32.html\">i32</a>&gt; for <a class=\"enum\" href=\"wasmtime/enum.Val.html\" title=\"enum wasmtime::Val\">Val</a>",synthetic:false,types:["wasmtime::values::Val"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.i64.html\">i64</a>&gt; for <a class=\"enum\" href=\"wasmtime/enum.Val.html\" title=\"enum wasmtime::Val\">Val</a>",synthetic:false,types:["wasmtime::values::Val"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.f32.html\">f32</a>&gt; for <a class=\"enum\" href=\"wasmtime/enum.Val.html\" title=\"enum wasmtime::Val\">Val</a>",synthetic:false,types:["wasmtime::values::Val"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.f64.html\">f64</a>&gt; for <a class=\"enum\" href=\"wasmtime/enum.Val.html\" title=\"enum wasmtime::Val\">Val</a>",synthetic:false,types:["wasmtime::values::Val"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"enum\" href=\"wasmtime/enum.AnyRef.html\" title=\"enum wasmtime::AnyRef\">AnyRef</a>&gt; for <a class=\"enum\" href=\"wasmtime/enum.Val.html\" title=\"enum wasmtime::Val\">Val</a>",synthetic:false,types:["wasmtime::values::Val"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;RuntimeValue&gt; for <a class=\"enum\" href=\"wasmtime/enum.Val.html\" title=\"enum wasmtime::Val\">Val</a>",synthetic:false,types:["wasmtime::values::Val"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"wasmtime/struct.HostRef.html\" title=\"struct wasmtime::HostRef\">HostRef</a>&lt;<a class=\"struct\" href=\"wasmtime/struct.Trap.html\" title=\"struct wasmtime::Trap\">Trap</a>&gt;&gt; for <a class=\"struct\" href=\"wasmtime/wasm/struct.wasm_trap_t.html\" title=\"struct wasmtime::wasm::wasm_trap_t\">wasm_trap_t</a>",synthetic:false,types:["wasmtime::wasm::wasm_trap_t"]},];
implementors["wasmtime_jit"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;ValidatingParserConfig&gt; for <a class=\"struct\" href=\"wasmtime_jit/struct.Features.html\" title=\"struct wasmtime_jit::Features\">Features</a>",synthetic:false,types:["wasmtime_jit::context::Features"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()